# Generated by Django 3.1.3 on 2020-12-03 13:26

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название игры')),
                ('description', models.TextField(verbose_name='Описание')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message="Can't be less than 0 board game")], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('add_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('img', models.ImageField(upload_to='bgpictures/', verbose_name='Обложка игры')),
            ],
        ),
    ]
