# Generated by Django 3.1.3 on 2021-01-20 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0002_auto_20201203_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='slug',
            field=models.SlugField(default='lol', verbose_name='Название для URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 20, 22, 34, 38, 409644, tzinfo=utc), verbose_name='Дата добавления'),
        ),
    ]
