# Generated by Django 3.1.3 on 2021-01-20 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0003_auto_20210121_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 20, 22, 35, 22, 991644, tzinfo=utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Название для URL'),
        ),
    ]
