# Generated by Django 3.1.3 on 2021-02-04 13:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0008_auto_20210202_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 4, 13, 24, 24, 621000, tzinfo=utc), verbose_name='Дата добавления'),
        ),
    ]
