# Generated by Django 3.1.3 on 2021-02-15 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0009_auto_20210204_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 15, 9, 20, 44, 78796, tzinfo=utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Название для URL'),
        ),
    ]
