# Generated by Django 3.1.3 on 2021-02-15 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0010_auto_20210215_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 15, 9, 49, 59, 677796, tzinfo=utc), verbose_name='Дата добавления'),
        ),
    ]
