# Generated by Django 3.1.3 on 2021-02-16 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0012_auto_20210215_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus', models.CharField(max_length=255, verbose_name='Русское слово')),
                ('eng', models.CharField(max_length=255, verbose_name='Английский перевод')),
            ],
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 13, 10, 49, 263808, tzinfo=utc), verbose_name='Дата добавления'),
        ),
    ]
