# Generated by Django 3.1.3 on 2021-02-21 23:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0013_auto_20210216_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabModel',
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 21, 23, 3, 50, 642000, tzinfo=utc), verbose_name='Дата добавления'),
        ),
    ]
