# Generated by Django 3.1.3 on 2021-02-22 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0016_auto_20210222_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 22, 11, 49, 33, 620412, tzinfo=utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена для всей корзины'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='price_for_product',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена для товара'),
        ),
    ]
