# Generated by Django 3.1.3 on 2021-03-17 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0017_auto_20210222_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='eng_name',
            field=models.CharField(blank=True, max_length=25, verbose_name='Название игры на английском'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 8, 19, 46, 251207, tzinfo=utc), verbose_name='Дата добавления'),
        ),
    ]
