# Generated by Django 3.1.3 on 2021-03-17 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0018_auto_20210317_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 8, 25, 36, 923007, tzinfo=utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='eng_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название игры на английском'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название игры'),
        ),
    ]
