# Generated by Django 3.2 on 2021-05-11 21:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
        ('boardgames', '0019_auto_20210317_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 11, 21, 35, 48, 351173, tzinfo=utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_registration.customer', verbose_name='Владелец'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
