# Generated by Django 3.2 on 2021-05-11 21:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0021_alter_boardgame_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 11, 21, 50, 45, 779923, tzinfo=utc), verbose_name='Дата добавления'),
        ),
    ]
